fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    hashi_stack: "https://github.com/voxpupuli/puppet-hashi_stack.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    yum: "https://github.com/voxpupuli/puppet-yum.git"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: ">= 6.0.0"
  symlinks:
    consul: "#{source_dir}"
