---
spec/spec_helper_acceptance.rb:
  unmanaged: false
Gemfile:
  optional:
    ':test':
      - gem: webmock
spec/spec_helper.rb:
  spec_overrides: "require 'spec_helper_local'"

.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
