name          'KyleAnderson-consul'
version       '0.0.1'
source        'https://github.com/solarkennedy/puppet-consul'
author        'Kyle Anderson <kyle@xkyle.com>'
license       'Apache License, Version 2.0'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'https://github.com/solarkennedy/puppet-consul'

dependency 'puppetlabs/stdlib'
dependency 'nanliu/staging'
