name          'KyleAnderson-consul'
version '0.4.6'
source        'https://github.com/solarkennedy/puppet-consul'
author        'Kyle Anderson <kyle@xkyle.com>'
license       'Apache License, Version 2.0'
summary       'Configures Consul by Hashicorp'
description   'Configures Consul by Hashicorp'
project_page  'https://github.com/solarkennedy/puppet-consul'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
dependency 'nanliu/staging', '>=0.4.0'
